# Generated by Django 5.2.11 on 2026-03-13 11:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGoals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_name', models.CharField(db_index=True, max_length=100)),
                ('target_amount', models.DecimalField(db_index=True, decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('deadline', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('target_category', models.ForeignKey(blank=True, help_text='Filter transactions by category for this goal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'deadline'],
                'indexes': [models.Index(fields=['user', 'status'], name='api_savings_user_id_9527aa_idx'), models.Index(fields=['deadline', 'status'], name='api_savings_deadlin_5b58c5_idx'), models.Index(fields=['start_date', 'user'], name='api_savings_start_d_108af5_idx')],
            },
        ),
    ]
