# Generated by Django 5.2.11 on 2026-03-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_quarterly_budget',
        ),
        migrations.RemoveIndex(
            model_name='budget',
            name='api_budget_user_id_909822_idx',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='quarterly',
        ),
        migrations.AddField(
            model_name='budget',
            name='quarterly_end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='quarterly_start_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'quarterly_start_date'], name='api_budget_user_id_e4f746_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['quarterly_start_date', 'quarterly_end_date'], name='api_budget_quarter_5a3d67_idx'),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('budget_type', 'quarterly')), fields=('user', 'type', 'budget_type', 'quarterly_start_date'), name='unique_quarterly_budget'),
        ),
    ]
