# Generated by Django 5.2.11 on 2026-03-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recurringtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='material_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
