services:
  pt-paisatrack:
    image: 147.79.66.211:3000/docker/financemanage-finance_backend:V1
    container_name: pt-paisatrack
    restart: always
    build:
      context: .
      dockerfile: Dockerfile

    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:pt-paisatrack

    ports:
      - "8200:8000"

    labels:
      - kompose.service.type=NodePort
      - kompose.service.expose=true
      - kompose.service.nodeport=30200
    depends_on:
      - pt-db-paisatrack
  pt-db-paisatrack:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: humbingo
      POSTGRES_DB: pt-db-paisatrack
      POSTGRES_PASSWORD: Welcome@1

    volumes:
      - ./pt-db-paisatrack:/var/lib/postgresql/data

    ports:
      - "5600:5432"
